CREATE TABLE IF NOT EXISTS public."points"
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(255),
    address character varying(255),
    city character varying(255),
    uf character varying(2),
    initial_hour character varying(2),
    end_hour character varying(2),
    email character varying(255),
    phone_number character varying(14)
);