CREATE TABLE IF NOT EXISTS public."users"
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(255),
    email character varying(255),
    password character varying(255)
);